name: Terraform

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
          
      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Find all Terraform directories
        id: find_dirs
        run: |
          # Find directories containing .tf files, including subdirectories
          find . -type f -name "*.tf" -exec dirname {} \; | sort -u > dirs.txt
          # Print the directories for debugging
          cat dirs.txt

      - name: Terraform Init
        run: |
          # Iterate over each directory in dirs.txt and run terraform init
          while IFS= read -r dir; do
            echo "Running terraform init in $dir"
            (cd "$dir" && terraform init)
          done < dirs.txt

      - name: Terraform Validate
        run: |
          # Iterate over each directory in dirs.txt and run terraform validate
          while IFS= read -r dir; do
            echo "Running terraform validate in $dir"
            (cd "$dir" && terraform validate)
          done < dirs.txt
        
      - name: Install TFlint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      - name: TFlint
        run: |
          # Iterate over each directory in dirs.txt and run tflint
          while IFS= read -r dir; do
            echo "Running tflint in $dir"
            (cd "$dir" && tflint)
          done < dirs.txt
      
      - name: Install tfsec
        run: |
          curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash
      
      - name: tfSec
        run: |
          # Iterate over each directory in dirs.txt and run tfsec
          while IFS= read -r dir; do
            echo "Running tfsec in $dir"
            # (cd "$dir" && tfsec)
          done < dirs.txt
      
      - name: Terraform Plan
        run: |
          # Iterate over each directory in dirs.txt and run terraform plan
          while IFS= read -r dir; do
            echo "Running terraform plan in $dir"
            (cd "$dir" && terraform plan)
          done < dirs.txt

      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          # Iterate over each directory in dirs.txt and run terraform apply
          while IFS= read -r dir; do
            echo "Running terraform apply in $dir"
            (cd "$dir" && terraform apply -auto-approve)
          done < dirs.txt
