name: Terraform

on: 
  push:
    branches: 
    - main
  pull_request:
  
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
          
      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Find all Terraform directories
        id: tf_dirs
        run: |
          dirs=$(find . -type f -name "*.tf" -exec dirname {} \; | sort -u)
          # Create a temporary file to store the directories
          echo "$dirs" > dirs.txt
          # Set the environment variable from the file
          echo "TF_DIRS=$(cat dirs.txt)" >> $GITHUB_ENV

      - name: Terraform Init
        run: |
          # Read the directories from the environment variable
          for dir in ${{ env.TF_DIRS }}; do
            echo "Running terraform init in $dir"
            (cd "$dir" && terraform init)
          done

      - name: Terraform Validate
        run: |
          # Read the directories from the environment variable
          for dir in ${{ env.TF_DIRS }}; do
            echo "Running terraform validate in $dir"
            (cd "$dir" && terraform validate)
          done
        
      - name: Install TFlint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      - name: TFlint
        run: |
          # Read the directories from the environment variable
          for dir in ${{ env.TF_DIRS }}; do
            echo "Running tflint in $dir"
            (cd "$dir" && tflint)
          done
      
      - name: Install tfsec
        run: |
          curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash
      
      - name: tfSec
        run: |
          # Read the directories from the environment variable
          for dir in ${{ env.TF_DIRS }}; do
            echo "Running tfsec in $dir"
            (cd "$dir" && tfsec)
          done
      
      - name: Terraform Plan
        run: |
          # Read the directories from the environment variable
          for dir in ${{ env.TF_DIRS }}; do
            echo "Running terraform plan in $dir"
            (cd "$dir" && terraform plan)
          done

      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          # Read the directories from the environment variable
          for dir in ${{ env.TF_DIRS }}; do
            echo "Running terraform apply in $dir"
            (cd "$dir" && terraform apply -auto-approve)
          done
