name: Terraform

on: 
  push:
    branches: 
    - main
  pull_request:
  
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
          
      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Terraform Init
        run: terraform init

      - name: Terraform validate
        run: terraform validate
        
      - name: Install TFlint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      - name: TFlint
        run: tflint
      
      - name: install tfsec
        run: |
          curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash
      
      - name: tfSec
        run: tfsec
      
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
      
      - name: Post Plan Comment
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const planOutput = fs.readFileSync('plan.out', 'utf8');
            const issue_number = context.payload.pull_request.number;
            github.rest.issues.createComment({
              ...context.repo,
              issue_number,
              body: `## Terraform Plan Result\n\`\`\`\n${planOutput}\n\`\`\``
            }); 
            
      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
